server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://omnistack:${PASSWORD_DB}@omnistack.l7tkn.mongodb.net/alura-stickers?retryWrites=true&w=majority
      authentication-database: admin